site_name: API Tradutora
site_description: Documentação da API Tradutora
site_author: Pedro
repo_url: https://github.com/FreitasProcopio/API_WAW/
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
nav:
  - Home: index.md
  - API:
      - Visão Geral: API/routes.md
      - CRUD:
        - Criar as palavras: API/CRUD/create.md
        - Ler as palavras: API/CRUD/all.md
        - Atualizar as palavras: API/CRUD/update.md 
        - Deletar as palavras: API/CRUD/delete.md 

      - Searching:  
          - Buscar imagem por Lingua: API/Searching/image.md
          - Buscar por Tipo: API/Searching/type.md
          - Buscar por Língua: API/Searching/language.md
          - Buscar por Povo: API/Searching/people.md
